### 用户注册
POST {{localHost}}/user/account/register
Content-Type: application/json

{
  "mobile": "13501294164",
  "password": "123456"
}

### 用户登陆
POST {{localHost}}/account/login
Content-Type: application/json

{
  "mobile": "13501294164",
  "password": "123456",
  "method": "mobile"
}

> {% client.global.set("token", response.body.data.token) %}

### 获取用户详情
GET {{localHost}}/user/1
Authorization: Bearer {{token}}


### 搜索用户
GET {{localHost}}/user/search?keyword=Fate
Authorization: Bearer {{token}}