### 用户注册
POST http://localhost:9501/account/register
Content-Type: application/json

{
  "mobile": "13501294164",
  "password": "123456"
}

### 用户登陆
POST http://localhost:9701/account/login
Content-Type: application/json

{
  "mobile": "13501294164",
  "password": "123456",
  "method": "mobile"
}

> {% client.global.set("token", response.body.data.token) %}

### 获取用户详情
GET http://localhost:9501/user/1
Authorization: Bearer {{token}}


### 搜索用户
GET http://localhost:9702/user/search?keyword=Fate
Authorization: Bearer {{token}}