apiVersion: v1
kind: Service
metadata:
  name: user-web-server
spec:
  selector:
    app: user-web-server
  ports:
    - name: http-user-web-sever
      protocol: TCP
      port: 9701
      targetPort: 9501
  type: NodePort