apiVersion: "v1"
kind: ConfigMap
metadata:
  name: user-web
  labels:
    app: user-web
data:
  # 服务配置
  server_name: user-web-server
  server_host: 0.0.0.0

  # jwt 配置
  jwt_key: Ep<4Iy#2Im~4Ab^8Px;6Oj.5Hi^8Yh)6
  jwt_expire: "86400"
  jwt_issuer: qvbilam-user

  # user-server 配置
  user-server_name: user-server
  user-server_host: user-server
  user-server_port: "9801"
