apiVersion: "v1"
kind: ConfigMap
metadata:
  name: user-web
  labels:
    app: user-web
data:
  # 服务配置
  server_name: "user-web"
  server_host: "0.0.0.0"
  # user-server 配置
  user_server_name: "user-server"
  user_server_host: "user-server"
  user_server_port: "9801"
  # public-server 配置
  public_server_name: "public-server"
  public_server_host: "public-server"
  public_server_port: "9803"
