# user.deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-user
  labels:
    app: web-server-user
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-server-user
  template:
    metadata:
      labels:
        app: web-server-user
        version: v1.0
    spec:
      containers:
        - name: user-server
          image: registry.cn-hangzhou.aliyuncs.com/qvbilam/web-server-user:1.0.0
          imagePullPolicy: Always
          ports: # 容器内部使用端口
            - containerPort: 9501
          env:
            # 服务配置
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: server_name
                  name: user-web

            # jwt 配置
            - name: JWT_KEY
              valueFrom:
                configMapKeyRef:
                  key: jwt_key
                  name: user-web
            - name: JWT_EXPIRE
              valueFrom:
                configMapKeyRef:
                  key: jwt_expire
                  name: user-web
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  key: jwt_issuer
                  name: user-web

            # user-server 配置
            - name: USER-SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: user-server_host
                  name: user-web
            - name: USER-SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: user-server_port
                  name: user-web
            - name: USER-SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: user-server_name
                  name: user-web


          resources:
            limits:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ali-image-key