apiVersion: v1
kind: Service
metadata:
  name: user-web-server
  labels:
    app: qvbilam-http
spec:
  selector:
    app: user-web
  ports:
    - name: http-server-user
      protocol: TCP
      port: 9701
      targetPort: 9501
  type: NodePort