apiVersion: "v1"
kind: ConfigMap
metadata:
  name: user-web
  labels:
    app: user-web
data:
  # 服务配置
  server_name: "web-server-user"
  server_host: "0.0.0.0"
  port: "9501"

  # jwt 配置
  jwt_key: "Ep<4Iy#2Im~4Ab^8Px;6Oj.5Hi^8Yh)6"
  jwt_expire: "86400"
  jwt_issuer: "qvbilam-user"

  # user-server 配置
  user-server_name: "api-server-user"
  user-server_host: "api-server-user"
  user-server_port: "9801"
