apiVersion: v1
kind: Service
metadata:
  name: web-server-user
spec:
  selector:
    app: web-server-user
  ports:
    - name: web-server-user
      protocol: TCP
      port: 9701
      targetPort: 9501
  type: NodePort